
Evaluating others and objects is very common. Generally speaking evaluations can be made with only very little information if asked for one (BRON). It thus might not be surprising that evaluations of generally evaluated neutral objects can be changed rather quickly (BRON) and easily. The mere repetitive exposure of a neutral object can result in a more positive evaluation of this object (BRON: mere exposure). Another intensively studied mechanism of influencing people's evaluation is through the process of evaluative conditioning (EC). The repetitive co-occurrence of a valenced stimulus called unconditioned stimulus(US) with a neutral stimulus called conditioned stimulus (CS) can result in a change of the evaluated valence of the CS (BRON). This effect has been shown consistently when both the CS and US were shown above the level of awareness. A wide used definition of Evaluative Conditioning is an effect that is 'a change in the valence of a stimulus that results from pairing the stimulus with another stimulus' (De Houwer.. 2001 (Q: Gast 2012))
Keeping this in mind dual-process theories would predict that this change of valence of the CS could happen through an __effortless and automatic__ process (BRON: Gawronski &amp; Bodenh.). __More?__

## Theoretical implications of subliminal EC effects
To dual process theories it is of importance that a reliable EC effect can be obtained with parts of the learning phase happening in an automatic and effortless manner. The goal of this study is to find an EC effect in a paradigm where the presentation of the CS is below awareness. If it would be possible to show that a EC effect can be found when the CS was not seen consciously it would indicate that the learning process could actually be explained by a dual-process model.

## Definition of subliminality/awareness

__Talk about subliminal presentation time__
__Talk about unaware (Dehaene stuff)__

## Subliminal paradigms in EC research

Recent work by Fazio (BRON) claimed that an EC effect can be shown when the __CS__ is shown subliminally. The effect is explained by a misattribution account (BRON). The proposed mechanism is that the negative or positive valence that is brought across by the US is misattribution to the CS. This in consequence results in a more positive/negative evaluation of the CS (BRON: __What is the DV used?__). Other studies also claim that they have demonstrated an EC effect with a  partly subliminal stimulus presentation (__BRON??__). Additionally Galli and Gorn (BRON) showed that a semantic transfer of meaning to brands is possible when the brand name is shown subliminally. 

However, other studies have shown that awareness of the contingency between the CS and US seems to be necessary to find an EC effect ([@stahl_respective_2009] BRON: Stahl). Even though the CS and US have been shown supraliminally, if participants could not recall the valence of the US paired with a certain CS the EC effect was absent. (__Talk about counter arguments of Huetter?__)
Other studies also showed that once the CS was presented subliminally, e.g. outside of the visual field, the EC effect was absent even though the stimulus was identified above chance (BRON: Pleyer &amp; Corneille??). 
An approach to control for the visibility of the CS is an online measure of visibility. Here after each trial including a subliminal stimulus the participant is shown a range of possible CS and has to select the stimulus they thought to have seen just before. When applying this conservative measure of visibility to a study and only analyzing trials where the visibility of the CS, which was presented for 30ms, was around, but not clearly above, chance no EC effect could be found (Stahl, in prep).


A recent meta analysis was also not able to give a conclusive answer on the question whether an EC effect was stable throughout paradigms with a subliminal CS/US (BRON Hofman) and thus concluded that more research is necessary to shed light into that question. 

## Goal of this study

The presentation time of the supposedly subconscious stimulus needs to be evaluated carefully. Pratte and Rouder for example show that under certain conditions very short presented stimuli can be detected and reported (BRON: Pratte and Rouder). It appears when controlling for the visibility of a stimulus, as done in the  recent study by Stahl (in prep), an evaluative conditioning effect with subliminally presented stimuli cannot be obtained.

It is thus a central aim of this study to find an EC effect with a strictly subliminally presented CS and looking for possible moderators. 

## Moderation of EC effect through relevance of CS-US combination and CS relevance to current need states

We can sum up that there are two rather distinct positions concerning the possibility of an EC effect with a subliminally presented CS. On the one hand showing an EC effect with subliminal paradigms and on the other hand stating that when subliminallity is controlled for strictly, no EC effect can be found. One possible explanation for this absence of an effect in some cases, could be that certain variables might moderate the EC effect.
One possible moderator, which has been identified recently in an EC like paradigm, was relevance of the CS-US relation and a need state to attend the CS (Verwijmeren BRON). In this study a water brand, presented subliminally as a picture during the learning phase, was chosen more likely when the participant was thirsty, compared to not thirsty, and when the US had relevance towards the concept of drinking. When either moderator was not present no effect on choice was found. Even though no effect was observed on an evaluative measure it appears promising to apply this paradigm to an experiment of evaluative conditioning, additionally controlling strictly for visibility of the CS. 

## The present study

In this study the paradigm by Verwijmeren et al (BRON) will be used as a global framework. However, one major change to the study of Verwijmeren et al (BRON) is an online visibility check to ensure that the relevance does not simply raise the motivation of the participant which in turn could result in a better visibility of the supposedly subconscious stimuli. A recent study by Pratte &amp; Rouder [@pratte_task-difficulty_2009] showed that when mixing different presentation times stimuli shown as short as __8,5ms??__ were __detected and recognized?__. The proposed reason for this effect was that the motivation to participate actively in the study was raised when some stimuli were easily visible. Being thirsty, which can be seen as the major need in humans (BRON?), might as well result in a higher motivation to look for pictures of water bottles (CS) which in turn results in a better visibility of the stimuli. 

Another important change to the original study of Verwijmeren (BRON), which taking care of criticism on subconscious presentation paradigms by Pratte and Rouder (BRON), is that subliminal and supraliminal stimuli will be presented within participant. (__leave it out?__)

Summarizing, in this study we will induce thirst with a between subject manipulation. As the CS we will have water bottles and airplane logos. 
We hypothesize that only when participants are thirsty and the CS is relevant to that, we we can find a subsequent effect on a liking measure. 
As in the study by Verwijmeren et al. (BRON) we will use relevant and irrelevant US when it comes to the concept of thirst and water. The same fearful faces (irrelevant to thirst and water CS) and disgusted faces (relevant to the thirst and water CS) will be used. We hypothesize that only when the US is relevant to the connection and the need is activated, an EC effect will be observed. Additionally a mere expose condition will be included, where water bottles and airplane company logo's are shown subliminally and supraliminally without a US following. We expect this to result in a better evaluation of the CS (possibly depending on the thirst condition). 

Additionally to the study of Verwijmeren et al (BRON) we will also pair the CS with IAPS pictures (BRON) rated high in disgust. This additional condition should shed light into the question whether the effect can only be observed when a face is transporting the information of disgust or also when the affect of disgust is induced. When an effect is only observed in the disgusted face condition but not in the disgusting IAPS condition it might be in line with a misatribution hypothesis. The negative affect induced by the IAPS picture might be attribute to the picture itself. However, when seeing a CS and immediately afterwards a face looking disgusted, it might be seen as a reaction of the person towards the previously shown stimulus (e.g. a water bottle).
Disgusted faces might in that case only have an effect on water bottles when participants are thirsty and thus likely have the goal to drink. When not having the goal to fly for example, but seeing a fearful face preceded by a plane logo this logo might not be evaluated more negatively, since the goal is not activated. 

As in the study of Verwijmeren et al (BRON) we will measure a hypothetical choice of water brands or plane companies afterwards and have an evaluative measure of each brand/product. It is of high interest whether we can find an effect on the evaluative measure, unlike to the study of Verwijmeren et al (BRON). When only finding a measure on choice we would have to reconsider the theoretical implications of this study __MORE! What would it mean?? Not EC but AC?__


# Methods

## Sample

__Power Analysis:__

A sample of __??__ participants took part in this study. A sensitivity analysis revealed that an effect as small as __????__ can be found with this sample size with a power of 1 - beta = .95, classified by Cohen as a __??__ effect (BRON: Cohen). The design was a 2 (thirst manipulation: yes/no) x 4 (US: disgust faces/ disgust IAPS pictures/ Fear faces/ no US) x 2 (CS: relevant to thirst[water bottles]/ irrelevant to thirst [airplane logos] ) x 2 (presentation time CS: 30ms/ 1000ms). The first factor was manipulated between participants, all others within.


## Material

As CSs for the thirst relevant condition we used 8 water bottles, all with a different logo found in an online search. For the thirst irrelevant condition we used 8 pictures of airplane companies. The two sets resulted from a pilot study were a larger set of bottles and airplane company logo's had to be rated, and neutrally scoring pictures were selected. No selected picture was reported as known by more than 6.6 % of the participants (N = 31) from this pilot study.

Each CS was presented 5 times, either with 5 different US from a specific category or 5 times without a US.As US we used 5 pictures of faces looking disgusted and 5 pictures of faces looking fearful (Bron: RAFD). Those were the same US as in the study by Verwijmeren et al (BRON). The US that were supposed to only transfer the affect of disgust were selected from the IAPS collection(BRON: IAPS), based on disgust ratings around 1 SD above the average disgust ratings (BRON: Libkuman, 2007). 

A colored pixel mask was created, used as a premask in every trial, including the supraliminal trials. It was additionally used as a post-mask in the mere exposure trials.

## Procedure

__CS introduced to participants as water brands or airplaine companies?__
Participants were told that they would see a lot of pictures, some very shortly. It was their task to identify those, shortly presented pictures. There were no further instruction on how to react to all other pictures. They were however told, that it was a difficult task to identify those pictures and that they had to guess, when not sure.

One trial was constructed as follows: A colored, squared sized (400 x 400 pixel), pre mask in the middle of the screen announced every trial. It was shown for _???? ms_. Immediately afterwards a CS was shown, with the same size as the pre-mask. Depending on the condition it was shown for _???ms_ or for _1000ms?_. Without a gap in between the US was shown, also functioning as a postmask. The US had a size of 512 x 384 pixel. The US was shown for ___??ms__ in the short Cs presentation trial and for ___??ms__ in the longer CS presentation trial, resulting in a total trial duration of _??ms_ for each trial. Afterwards the screen was cleared. 

After trials with a short CS presentation a screen appeared showing all 8 objects (either water bottles or plane logo's depending on the condition in the trial). Participants had to select an object by pressing a corresponding number to report which object they thought to have seen in the previous trial. The order of object presentation was randomized for each trial.

Since we decided not to have an online visibility check for trials in which the CS was shown for 1000ms we included 5 trials with a new bottle and 5 trials with a new airplane logo followed by a neutral US for slightly longer than the subconscious CS, namely for __????ms__. This was in order to keep the motivation to detect a shortly presented CS high (BRON: Pratte and Rouder) since it was easier to detect the CS in these cases. These trials were not included in the measure of the depending variable, since no hypothesis existed about these trials. We only looked at the rate of correct detection, since it should have been rather easy in this case. __Participants showing a ???? deviation from the mean correct detection rate were excluded in the analysis.__ [What do you think?, just a first idea]

This setup resulted in a total of 90 trials that were part of this learning phase. Since the same US were used for subliminal and supraliminal CS presentation trials, the CS category were assigned at random for each participant individually to a fixed pair of presentation time and US type. 

After the learning phase evaluative ratings and choices were collected. The order in which  the two depended variables were collected were counterbalanced over participants. In the rating measurement, each critical water bottle and each airplane logo were shown separately and asked to be rated on a 9 point likert scale. Water bottle ratings were always asked first and afterwards the ratings of the airplane logo's.

In the choice measure participants were instructed to choose a bottle, based on which they would like to drink. All 8 bottles were shown on a screen with corresponding number underneath. After one number was chosen for the selected bottle the resulting 7 bottles were shown and a new decision was asked for. This process was repeated until 7 decisions had been made, while the order of stimuli was at random for every new presentation.
The same procedure was repeated with the airplane logo's.

In the end the following demographic items and debriefing questions were asked: age, study, gender, overall idea of goal of study, reason for thirst manipulation (if in the condition), further comments (__anything else?__).

# Results



# Discussion

We failed to replicate the original finding.

# References
</pre></body></html>